In [1]:
from sklearn import preprocessing
import numpy as np
import pandas as pd
import pylab
# Get dataset
data = pd.read_csv(r'/Users/sirigowda/Documents/Normalised Data/AnalysedData.csv')

Matplotlib is building the font cache; this may take a moment.


In [3]:
from sklearn.preprocessing import MinMaxScaler
normaliser=MinMaxScaler()
df=normaliser.fit_transform(data)

In [8]:
print(df)

[[0.94       0.92857143 0.75       ... 0.91346154 1.         0.92063492]
 [0.68       0.53571429 0.75       ... 0.66346154 1.         0.66666667]
 [0.52       0.42857143 0.5        ... 0.38461538 1.         0.6031746 ]
 ...
 [0.8        1.         1.         ... 0.88461538 1.         0.93650794]
 [0.44       0.39285714 0.75       ... 0.5224359  0.         0.61904762]
 [0.74       0.75       0.75       ... 0.71794872 0.         0.79365079]]
